services:
# my-sql database
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db-volume:/var/lib/mysql

# volumes configuration
volumes:
  mysql-db-volume:
    driver: local
